name: Set Environment Variables

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    env:
      PUBLIC_KEY: ${{ secrets.EMAIL_JS_PUBLIC_KEY }}
      SERVICE_ID: ${{ secrets.EMAIL_JS_SERVICE_ID }}
      TEMPLATE_ID: ${{ secrets.EMAIL_JS_TEMPLATE_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use secret
